# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    limitService:
        class: FrontBundle\Service\Limit
    apiViolation:
        class: FrontBundle\EventListener\ApiViolationListener
        arguments: [ '@service_container' ]
        tags:
            - { name: kernel.event_listener, event: api.violation, method: logViolation }